import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage1dark">Homepage1Dark</Link>
        </li>
        <li>
          <Link to="/homepage7dark">Homepage7Dark</Link>
        </li>
        <li>
          <Link to="/homepage2dark">Homepage2Dark</Link>
        </li>
        <li>
          <Link to="/homepage5dark">Homepage5Dark</Link>
        </li>
        <li>
          <Link to="/homepage6dark">Homepage6Dark</Link>
        </li>
        <li>
          <Link to="/homepage3dark">Homepage3Dark</Link>
        </li>
        <li>
          <Link to="/popupplacebid">PopupPlaceBid</Link>
        </li>
        <li>
          <Link to="/hoverdarkhome">HoverDarkHome</Link>
        </li>
        <li>
          <Link to="/hoverdarkexplore">HoverDarkExplore</Link>
        </li>
        <li>
          <Link to="/hoverdarkpage">HoverDarkPage</Link>
        </li>
        <li>
          <Link to="/hoverdarkcreate">HoverDarkCreate</Link>
        </li>
        <li>
          <Link to="/hoverdarkblog">HoverDarkBlog</Link>
        </li>
        <li>
          <Link to="/hoverdarkcontact">HoverDarkContact</Link>
        </li>
        <li>
          <Link to="/hoverdarkuser">HoverDarkUser</Link>
        </li>
        <li>
          <Link to="/profileeditprofile2dark">ProfileEditProfile2Dark</Link>
        </li>
        <li>
          <Link to="/contactdark">ContactDark</Link>
        </li>
        <li>
          <Link to="/profiledashboarddark">ProfileDashboardDark</Link>
        </li>
        <li>
          <Link to="/profileeditprofiledark">ProfileEditprofileDark</Link>
        </li>
        <li>
          <Link to="/profilefollowingdark">ProfileFollowingDark</Link>
        </li>
        <li>
          <Link to="/profilefavoritesdark">ProfileFavoritesDark</Link>
        </li>
        <li>
          <Link to="/profilefollowingdark1">ProfileFollowingDark1</Link>
        </li>
        <li>
          <Link to="/collectiondetailsdark">CollectionDetailsDark</Link>
        </li>
        <li>
          <Link to="/addnewnftdark">AddNewNFTDark</Link>
        </li>
        <li>
          <Link to="/helpcenterdark">HelpCenterDark</Link>
        </li>
        <li>
          <Link to="/faqsdark">FAQsDark</Link>
        </li>
        <li>
          <Link to="/profileinventorydark">ProfileInventoryDark</Link>
        </li>
        <li>
          <Link to="/itemdetailsauctionshistorydark">
            ItemDetailsAuctionsHistoryDark
          </Link>
        </li>
        <li>
          <Link to="/itemdetailsauctionsbiddark">
            ItemDetailsAuctionsBidDark
          </Link>
        </li>
        <li>
          <Link to="/itemdetailsauctionsdark">ItemDetailsAuctionsDark</Link>
        </li>
        <li>
          <Link to="/itemdetailsbiddark">ItemDetailsBidDark</Link>
        </li>
        <li>
          <Link to="/itemdetailshistory">ItemDetailsHistory</Link>
        </li>
        <li>
          <Link to="/exploreleftbardark">ExploreLeftBarDark</Link>
        </li>
        <li>
          <Link to="/explore4itemdark">Explore4ItemDark</Link>
        </li>
        <li>
          <Link to="/exploregriddark">ExploreGridDark</Link>
        </li>
        <li>
          <Link to="/explorebannerdark">ExploreBannerDark</Link>
        </li>
        <li>
          <Link to="/itemdetailsdark">ItemDetailsDark</Link>
        </li>
        <li>
          <Link to="/blogdetails2dark">BlogDetails2Dark</Link>
        </li>
        <li>
          <Link to="/connectwalletdark">ConnectWalletDark</Link>
        </li>
        <li>
          <Link to="/rankingdark">RankingDark</Link>
        </li>
        <li>
          <Link to="/logindark">LoginDark</Link>
        </li>
        <li>
          <Link to="/signupdark">SignupDark</Link>
        </li>
        <li>
          <Link to="/blog2dark">Blog2Dark</Link>
        </li>
        <li>
          <Link to="/blogdetails1dark">BlogDetails1Dark</Link>
        </li>
        <li>
          <Link to="/liveauctiondark">LiveauctionDark</Link>
        </li>
        <li>
          <Link to="/liveauctionbannerdark">LiveAuctionBannerDark</Link>
        </li>
        <li>
          <Link to="/blog1dark">Blog1Dark</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
